renderer.enabled=true
renderer.allowExternalCommand=false
renderer.defaultDurationSeconds=6
renderer.defaultAllowManualClose=true
renderer.defaultWindowWidth=420
renderer.defaultWindowHeight=180
renderer.defaultPlayerScreenX=0
renderer.defaultPlayerScreenY=0
renderer.defaultMapX=0
renderer.defaultMapY=0
renderer.defaultAlign=1

storage.listDataPluginClass=com.mdt.listdata.ListDataSystemPlugin
storage.bindUuidField=playerUuid
